/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import axios from 'axios';
import Link from 'next/link';


import React, { useState, useCallback, useEffect} from 'react';



const Home= () => {


    const [checkedItem, setCheckedItem] = useState('NHL');
    
    const handleChangeA = (event) => {
        setCheckedItem(event.target.id);
    };


  /*  setInterval(() =>{
     ( function async () {
      const res = await axios.get('/api/NHL/UpdateNHLstats')
     })()
   },)  */


 let date = new Date();
let hr = date.getHours();

if (hr === 23) {
    (async function() {
        try {
            const res = await axios.get('/api/NHL/UpdateNHLstats');
            console.log(res.data); // Log the response data
        } catch (error) {
            console.error('Error fetching data:', error);
        }
    })();
}



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* 
      <div className="container-fluid my-5">

      

        <div className='d-flex justify-content-center ps-4'
             style={{width: '400px', margin: '0 auto'}}>

            <div className="form-check" 
                 style={{width: '150px'}}>
                <input 
                    className="form-check-input fw-semibold fs-5 hover" 
                    type="checkbox" 
                    id="NHL" 
                    checked={checkedItem === 'NHL'} 
                    onChange={handleChangeA} 
                />
                <label className="form-check-label fs-5 hover" htmlFor="NHL">
                    NHL
                </label>
            </div>

            <div className="form-check form" 
                 style={{width: '150px'}}>
                <input 
                    className="form-check-input fw-semibold fs-5 hover" 
                    type="checkbox" 
                    id="WJC" 
                    checked={checkedItem === 'WJC'} 
                    onChange={handleChangeA} 
                />
                <label className="form-check-label fs-5 hover" htmlFor="WJC">
                    WJC
                </label>
            </div>

            <div className="form-check form" 
                 style={{width: '150px'}}>
                <input 
                    className="form-check-input fw-semibold fs-5 hover" 
                    type="checkbox" 
                    id="WCH" 
                    checked={checkedItem === 'WCH'} 
                    onChange={handleChangeA} 
                />
                <label className="form-check-label fs-5 hover" htmlFor="WCH">
                    WCH
                </label>
            </div>

            <div className="form-check form" 
                 style={{width: '150px'}}>
                <input 
                    className="form-check-input fw-semibold fs-5 hover" 
                    type="checkbox" 
                    id="SVK" 
                    checked={checkedItem === 'SVK'} 
                    onChange={handleChangeA} 
                />
                <label className="form-check-label fs-5 hover" htmlFor="SVK">
                    SVK
                </label>
            </div>
        </div>
        <hr />



        {
          checkedItem === 'NHL' && <NHL/>
        }
        {
          checkedItem === 'WJC' && <WJC/>
        }
        {
          checkedItem === 'WCH' && <WCH/>
        }
        {
          checkedItem === 'SVK' && <SVK/>
        }



       
      </div>
 */}

 

   <h4 className='text-center mt-5'>Explore the World of Hockey</h4>
   <h4 className='text-center mb-5'>
      Special thanks to <a href="http://hockey-live.sk" target="_blank" rel="noopener noreferrer">hockey-live.sk</a> for providing accurate and up-to-date data.
    </h4>


  <div className="container-fluid">
    <div className="row justify-content-center">

      <div className="col-11 col-md-3 mt-5">
         <h4 className='text-center'>NHL</h4>
         <div className='text-center cursor'>
          <Link href={'/NHL/Leading/Leading'}>
             <img src="./NHL/nhl.png" style={{width: '200px'}} alt="img" />
          </Link>
        </div>
      </div>

      <div className="col-11 col-md-3 mt-5">
         <h4 className='text-center'>WCH</h4>
         <div className='text-center cursor'>
          <Link href={'/WCH/Groups/Groups'}>
            <img src="./WCH/WCH.png" style={{width: '200px'}} alt="img" />
          </Link>
         </div>
      </div>

    </div>
  </div>



   
     

   


      <style>{`

      .cursor:hover {
         cursor: pointer;
      }

      .hero-paragraph {
        position: relative;
        max-width: 800px;
        margin: 0 auto;
        font-size: 20px;
      }

       .selection {
        position: relative;

       }

        .hover:hover {
          cursor: pointer;
         }
      `}</style>
    </>
  )
        }





export default Home